-- MySQL Script generated by MySQL Workbench
-- Wed Jan 23 01:55:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema peliculas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema peliculas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peliculas` DEFAULT CHARACTER SET utf8 ;
USE `peliculas` ;

-- -----------------------------------------------------
-- Table `peliculas`.`pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`pelicula` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `anio` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculas`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`sucursal` (
  `id` INT NOT NULL,
  `urbanizacion` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`cliente` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `fnac` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculas`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`genero` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculas`.`director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`director` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculas`.`actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`actor` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculas`.`sucursal_pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`sucursal_pelicula` (
  `idsucursal_pelicula` INT NOT NULL,
  `id_pelicula` INT NOT NULL,
  `id_sucursal` INT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`idsucursal_pelicula`),
  CONSTRAINT `fk_idpelicula_sucursal`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `peliculas`.`pelicula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idsucursal_sucursal`
    FOREIGN KEY (`id_sucursal`)
    REFERENCES `peliculas`.`sucursal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_idpelicula_idx` ON `peliculas`.`sucursal_pelicula` (`id_pelicula` ASC);

CREATE INDEX `fk_idsucursal_idx` ON `peliculas`.`sucursal_pelicula` (`id_sucursal` ASC);


-- -----------------------------------------------------
-- Table `peliculas`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`venta` (
  `id` INT NOT NULL,
  `id_pelicula` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `fecha_hora` DATE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idpelicula_venta`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `peliculas`.`pelicula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idcliente_venta`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `peliculas`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_idpelicula_idx` ON `peliculas`.`venta` (`id_pelicula` ASC);

CREATE INDEX `fk_idcliente_idx` ON `peliculas`.`venta` (`id_cliente` ASC);


-- -----------------------------------------------------
-- Table `peliculas`.`pelicula_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`pelicula_genero` (
  `idpelicula_genero` INT NOT NULL,
  `idgenero` INT NOT NULL,
  `idpelicula` INT NOT NULL,
  PRIMARY KEY (`idpelicula_genero`),
  CONSTRAINT `fk_idgenero_genero`
    FOREIGN KEY (`idgenero`)
    REFERENCES `peliculas`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idpelicula_genero`
    FOREIGN KEY (`idpelicula`)
    REFERENCES `peliculas`.`pelicula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_idgenero_idx` ON `peliculas`.`pelicula_genero` (`idgenero` ASC);

CREATE INDEX `fk_idpelicula_idx` ON `peliculas`.`pelicula_genero` (`idpelicula` ASC);


-- -----------------------------------------------------
-- Table `peliculas`.`pelicula_director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`pelicula_director` (
  `idpelicula_director` INT NOT NULL,
  `idpelicula` INT NOT NULL,
  `iddirector` INT NOT NULL,
  PRIMARY KEY (`idpelicula_director`),
  CONSTRAINT `fk_idpelicula_director`
    FOREIGN KEY (`idpelicula`)
    REFERENCES `peliculas`.`pelicula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_iddirector_director`
    FOREIGN KEY (`iddirector`)
    REFERENCES `peliculas`.`director` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_idpelicula_idx` ON `peliculas`.`pelicula_director` (`idpelicula` ASC);

CREATE INDEX `fk_iddirector_idx` ON `peliculas`.`pelicula_director` (`iddirector` ASC);


-- -----------------------------------------------------
-- Table `peliculas`.`pelicula_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculas`.`pelicula_actor` (
  `idpelicula_actor` INT NOT NULL,
  `idpelicula` INT NOT NULL,
  `idactor` INT NOT NULL,
  PRIMARY KEY (`idpelicula_actor`),
  CONSTRAINT `fk_idpelicula_actor`
    FOREIGN KEY (`idpelicula`)
    REFERENCES `peliculas`.`pelicula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idactor_actor`
    FOREIGN KEY (`idactor`)
    REFERENCES `peliculas`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_idpelicula_idx` ON `peliculas`.`pelicula_actor` (`idpelicula` ASC);

CREATE INDEX `fk_idactor_idx` ON `peliculas`.`pelicula_actor` (`idactor` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
